version = "2.0.0"
author = "disruptek"
description = "Google Cloud Platform (GCP) APIs"
license = "MIT"
requires "nim >= 0.20.0"
requires "openapi 3.1.0"
#requires "https://github.com/treeform/jwt.git >= 0.0.1"
requires "https://github.com/yglukhov/nim-jwt.git"
requires "https://github.com/disruptek/rest.git >= 1.0.0"

srcDir = "src"
